- name: Install selinux bindings
  yum: pkg=libselinux-python state=latest update_cache=yes

- name: Install nginx official repo
  template: src=nginx.repo.j2
            dest=/etc/yum.repos.d/nginx.repo
            owner=root group=root mode=0644

- yum: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - vim
    - mysql-server
    - git
    - nginx
    - curl

- name: Create betterplace user account
  user:
    name=betterplace
    shell=/bin/bash
    generate_ssh_key=true

- name: Assign authorized_key for each devop
  authorized_key:
    user=betterplace
    key="{{item.public_key}}"
    state=present
  with_items: devops
  no_log: true
  when: item.active == true

- name: Load chruby in .bashrc
  lineinfile: "
    dest=/home/betterplace/.bashrc
    state=present
    line='test -f /etc/profile.d/chruby.sh && source /etc/profile.d/chruby.sh'
  "
