---
- name: Remove authorized_keys for disabled user
  file: path=/home/{{item.username}}/.ssh/authorized_keys
        state=absent
  with_items: devops
  when: item.active == false
  no_log: true

- name: Remove user from wheel group
  user: name={{item.username}} groups=wheel state=absent
  with_items: devops
  when: item.active == false
  no_log: true
